# Generated by Django 4.0.5 on 2022-07-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_created_at_product_modified_at'),
        ('categories', '0003_delete_subcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Type',
        ),
    ]
