# Generated by Django 4.0.5 on 2022-07-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('red', 'red'), ('blue', 'blue'), ('grey', 'grey'), ('yellow', 'yellow'), ('green', 'green'), ('pink', 'pink'), ('orange', 'orange'), ('brown', 'brown'), ('violet', 'violet'), ('gold', 'gold'), ('silver', 'silver')], default='other', max_length=20),
        ),
    ]
