# Generated by Django 4.0.5 on 2022-07-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_rename_category_type'),
        ('products', '0005_product_created_at_product_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='categories.size'),
        ),
    ]
